# Generated by Django 4.2.2 on 2023-10-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('singer_name', models.CharField(max_length=200)),
                ('album_name', models.CharField(max_length=140)),
                ('song_file', models.FileField(upload_to='uploads')),
                ('genre', models.CharField(max_length=140)),
                ('song_image', models.ImageField(default='default.jpg', upload_to='song_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
